// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
// ```dart
/// import 'firebase_options.dart';
/// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiZnl-xGmw8cxAnWg9o7xSMWHaTnB3J5A',
    appId: '1:826212704198:web:cc8b4bfa9a3ece685e9cc7',
    messagingSenderId: '826212704198',
    projectId: 'dentaignose-a0427',
    authDomain: 'dentaignose-a0427.firebaseapp.com',
    storageBucket: 'dentaignose-a0427.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD02RiPzIcT20DnXfqu2aYen9mHdXJ_yFs',
    appId: '1:826212704198:android:91fca304d76aa2695e9cc7',
    messagingSenderId: '826212704198',
    projectId: 'dentaignose-a0427',
    storageBucket: 'dentaignose-a0427.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHW5CQthSIMEOdbkjiQE1wv_t9Z5ziPxE',
    appId: '1:826212704198:ios:d2f990ae6e520bea5e9cc7',
    messagingSenderId: '826212704198',
    projectId: 'dentaignose-a0427',
    storageBucket: 'dentaignose-a0427.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHW5CQthSIMEOdbkjiQE1wv_t9Z5ziPxE',
    appId: '1:826212704198:ios:976e9ac8d86bfe075e9cc7',
    messagingSenderId: '826212704198',
    projectId: 'dentaignose-a0427',
    storageBucket: 'dentaignose-a0427.appspot.com',
    iosBundleId: 'com.example.graduationProject.RunnerTests',
  );
}
